</td>
</tr>
<tr>
    <td height="323"></td>
</tr>
</table>
</div>
<div id="preload">
    <img src="menutrans3bis.jpg">
    <img src="menutrans4bis.jpg">
    <img src="menutrans5bis.jpg">
    <img src="menutrans6bis.jpg">
    <img src="menutrans7bis.jpg">
    <img src="menutrans8bis.jpg">
    <img src="menulat2bis.jpg">
    <img src="menulat3bis.jpg">
    <img src="menulat4bis.jpg">
    <img src="menulat5bis.jpg">
    <img src="menulat6bis.jpg">
    <img src="menulat7bis.jpg">
    <img src="menulat8bis.jpg">
    <img src="menulat9bis.jpg">
</div>
</div>
<script>
    $(".float").sideFollow();
</script>
</body>
</html>