<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>MAM Musique</title>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-69488539-1', 'auto');
        ga('send', 'pageview');

    </script>

    <link rel="stylesheet" type="text/css" href="style/main.css">
</head>

<body class="general-style">
<div align="left">
    <div align="center">
        <table>
            <tr>
                <td><img src="menutrans2.jpg"></td>
                <td><a id="jazzin_link" href="jazzin.php"></a></td>
                <td><a id="mamduo_link" href="mamduo.php"></a></td>
                <td><a id="mamtrio_link" href="mamtrio.php"></a></td>
                <td><a id="mamquartet_link" href="mamquartet.php"></a></td>
                <td><a id="guenaelle_link" href="guenaelle.php"></a></td>
                <td><a id="machine_link" href="machine.php"></a></td>
            </tr>
        </table>
        <table valign="top">
            <!--DWLayoutTable-->
            <tr>
                <td valign="top">
                    <table valign="top">
                        <tr><td><div><a id="accueil_link" href="accueil.php"></a></div></td></tr>
                        <tr><td><a id="actualite_link" href="actualite.php"></a></td></tr>
                        <tr><td><a id="concerts_link" href="concerts.php"></a></td></tr>
                        <tr><td><a id="presse_link" href="presse.php"></a></td></tr>
                        <tr><td><a id="discographie_link" href="discographie.php"></a></td></tr>
                        <tr><td><a id="jeune_link" href="jeune.php"></a></td></tr>
                        <tr><td><a id="credits_link" href="credits.php"></a></td></tr>
                        <tr><td><a id="contact_link" href="contact.php"></a></td></tr>
                    </table>
                </td>
                <td width="627" rowspan="2" valign="top" bgcolor="#C9935D">